# -*- coding: utf-8 -*-
"""zomato.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ozxviB7t8LbxeOXLslysy0unyaYGGJL

# EDA on Zomato Dataset
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

df = pd.read_csv("C:\\Users\\user\\Downloads\\Zomato-data-.csv")

df.head()

df.info()

df.shape

df.isnull().sum()

df.describe()

#converting rating into number
df['rate'] = df['rate'].str.replace('/5', '', regex=False)
df['rate'] = pd.to_numeric(df['rate'], errors='coerce')

#rating distribution
sns.histplot(df['rate'], bins=8, kde=True)
plt.show()

#online roder vs rating
sns.boxplot(x='online_order', y='rate', data=df)
plt.show()

#category count
sns.countplot(x='listed_in(type)', data=df)
plt.xticks(rotation=45)
plt.show()